SELECT  t.CHAR_YEAR, t.CHAR_MON ,CHAR_DESTINATION,  count(distinct CHAR_DESTINATION) 
FROM charter c
JOIN time_dim t
on c.CHAR_DATE=t.CHAR_DATE
group by t.CHAR_YEAR, t.CHAR_MON ,CHAR_DESTINATION, CHAR_TRIP
