SELECT CHAR_MON,CHAR_YEAR, c.CUS_CODE,CHAR_TRIP,CHAR_DISTANCE*MOD_CHG_MILE as 'Gross_Profit'
FROM charter c
join time_dim t
on c.CHAR_DATE=t.CHAR_DATE
join aircraft a
on c.AC_NUMBER=a.AC_NUMBER
join model m
on a.MOD_CODE = m.MOD_CODE
GROUP BY CHAR_MON,CHAR_YEAR,c.CUS_CODE,c.CHAR_TRIP
Order by CHAR_YEAR,CHAR_MON,c.CHAR_TRIP,c.CUS_CODE
