SELECT CHAR_YEAR, CHAR_MON, c.CHAR_PILOT,e.EMP_TITLE,e.EMP_LNAME ,e.EMP_FNAME,CHAR_TRIP,(c.CHAR_HOURS_FLOWN+c.CHAR_HOURS_WAIT) as Work_Time
FROM charter c
join time_dim t
on c.CHAR_DATE=t.CHAR_DATE
join employee e
on c.CHAR_PILOT=e.EMP_NUM
GROUP BY CHAR_YEAR, CHAR_MON,c.CHAR_PILOT,CHAR_TRIP
